version: '3'
services:
  app:
    image: go-app:1.0
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASS=mypassword
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    volumes:
      - ./app-data:/app/data
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=internship
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/db-data
      o: bind